"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = 'î‚  '

[gradle]
disabled = true

[java]
format = '[${symbol}(${version} )]($style)'
version_format = '${major}'
symbol = 'î™­ '
style = 'blue'

[kotlin]
format = '[${symbol}(${version} )]($style)'
symbol = 'î˜´ '
style = 'yellow'

[golang]
format = '[${symbol}(${version} )]($style)'
symbol = 'ï†  '
style = 'blue'

[rust]
format = '[${symbol}(${version} )]($style)'
symbol = 'îž¨ '
style = 'blue'

[nodejs]
format = '[${symbol}(${version} )]($style)'
style = 'blue'

[python]
format = '[${symbol}(${version} )]($style)'
symbol = 'îœ¼ '
style = 'blue'

[conda]
format = '[${symbol}(${version} )]($style)'
symbol = 'ðŸ…’ '
style = 'blue'

[package]
format = '[${symbol}${version}]($style) '
symbol = 'ï’‡ '
style = 'green'
